version: "3.3"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - "3000:3000"
